export const SHOW_TICKET_MODAL = 'SHOW_TICKET_MODAL';
export const CLOSE_TICKET_MODAL = 'CLOSE_TICKET_MODAL';

export const CREATE_TICKET = 'CREATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const VALIDATE_FAILURE = 'VALIDATE_FAILURE';

export const START_TICKET_TIMER = 'START_TICKET';
export const PAUSE_TICKET_TIMER = 'PAUSE_TICKET_TIMER';
export const FINISH_TICKET = 'FINISH_TICKET';
export const STOP_TICKET_TIMER = 'STOP_TICKET_TIMER';

export const ADD_SECOND_TO_TICKET = 'ADD_SECOND_TO_TICKET';
